some fixes

diff --git a/bug-repro b/bug-repro
--- a/bug-repro
+++ b/bug-repro
@@ -6,29 +6,34 @@ function do_lint {
   pylint --recursive=y --disable=W,C0114,C0115,C0116,R0903 -s=n .
 }
 
+function error {
+  echo "ERROR:" "$*"
+  exit 1
+}
+
 echo
 echo "========================================================================="
 echo ">>> Running 'pylint' in a local folder"
 echo "    pylint is expected to fail..."
 
 cd /code || exit 1
-do_lint && echo "ERROR: Expected to fail" && exit 1 || echo "PYLINT FAILED"
+do_lint && error "ERROR: Expected to fail" || echo "PYLINT FAILED"
 
 echo
 echo "========================================================================="
 echo ">>> Running 'pylint' in a mounted folder"
 echo "    for some reason, pylint succeeds when mounting a folder from MacOS host"
 
-cd /mounted_code || echo "Folder not mounted! use './run'" -a exit 1
+cd /mounted_code || error "Folder not mounted! use './run'"
 
 do_lint && echo "PYLINT SUCCEEDED" \
-  || echo "ERROR: expected pylint to succeed on the mounted folder (on MacOS host)"
+  || error "ERROR: expected pylint to succeed on the mounted folder (on MacOS host)"
 
 echo
 echo "========================================================================="
 echo ">>> RUNNING DIFF between folders"
 diff -r /code /mounted_code && echo "Folders are identical" \
-  || echo "ERROR: folders are supposed to be identical" -a exit 1
+  || error "ERROR: folders are supposed to be identical"
 
 echo
 echo "========================================================================="
diff --git a/verify-resolutions b/verify-resolutions
--- a/verify-resolutions
+++ b/verify-resolutions
@@ -6,23 +6,28 @@ function do_lint {
   pylint --recursive=y --disable=W,C0114,C0115,C0116,R0903 -s=n .
 }
 
+function error {
+  echo "ERROR:" "$*"
+  exit 1
+}
+
 echo
 echo "========================================================================="
 echo ">>> Verifying 'pyling' is still failing..."
 cd /code || exit 1
-do_lint && echo "ERROR: Expected to fail" && exit 1 || echo "PYLINT FAILED"
+do_lint && error "ERROR: Expected to fail" || echo "PYLINT FAILED"
 
 echo
 echo "========================================================================="
 echo ">>> The following sed replacement resolves the issue"
 sed -i 's/from module1 import Base/from module1.base import Base/' module1/derived.py \
-  || echo "ERROR: 'sed' failed..." -a exit 1
+  || error "ERROR: 'sed' failed..."
 
-do_lint && echo "PYLINT SUCCEEDED" || echo "ERROR: pylint was supposed to succeeded"
+do_lint && echo "PYLINT SUCCEEDED" || error "ERROR: pylint was supposed to succeeded"
 
 # restore
 sed -i 's/from module1.base import Base/from module1 import Base/' module1/derived.py \
-  || echo "ERROR: 'sed' (restore) failed..." -a exit 1
+  || error "ERROR: 'sed' (restore) failed..."
 
 echo
 echo "========================================================================="
@@ -30,7 +35,7 @@ echo ">>> Oddly enough, adding '__init__.py' in the local folder also solves it"
 cd /code
 touch "__init__.py"
 do_lint && echo "PYLINT SUCCEEDED" \
-  || echo "ERROR: pylint was supposed to succeed" -a exit 1
+  || error "ERROR: pylint was supposed to succeed"
 
 rm "__init__.py"
 
